name: flutterquiz
description: A new Flutter application.
publish_to: "none"
version: 2.3.7+61

# Release Version: 2.3.7 (do not remove or edit this)
environment:
  sdk: ^3.10.0

dependencies:
  app_tracking_transparency: ^2.0.6+1
  cached_network_image: ^3.4.1
  cloud_firestore: ^6.0.2
  country_code_picker: ^3.4.0
  dotted_border: ^3.1.0
  encrypt: ^5.0.3
  firebase_analytics: ^12.0.2
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  firebase_messaging: ^16.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cached_pdfview: ^0.4.3
  flutter_local_notifications: ^19.4.2
  flutter_pdfview: ^1.4.3
  flutter_svg: ^2.2.1
  flutter_tex: 4.0.9
  flutter_timezone: ^5.0.0
  flutter_widget_from_html: ^0.17.1
  google_fonts: ^6.3.2
  google_mobile_ads: ^6.0.0
  google_sign_in: ^7.2.0
  hive_flutter: ^1.1.0
  http: 1.3.0
  iabtcf_consent_info: ^3.4.0
  image_cropper: ^11.0.0
  image_picker: ^1.2.0
  in_app_purchase: 3.2.1
  in_app_purchase_android: ^0.4.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  ironsource_mediation: ^3.2.0
  just_audio: 0.9.46
  lottie: ^3.3.2
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pin_code_fields: ^8.0.1
  scratcher: ^2.5.0
  screenshot: ^3.0.0
  share_plus: ^12.0.0
  sign_in_with_apple: ^7.0.1
  unity_ads_plugin: ^0.3.27
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0
  youtube_player_flutter: ^9.1.3

dependency_overrides:
  flutter_widget_from_html: 0.16.0
  webview_flutter_plus: 0.4.7


dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/config/
    - assets/config/emojis/
    - assets/config/payment_methods/
    - assets/config/profile/
    - assets/config/sounds/
    - assets/images/
    - assets/images/bottom_nav_icons/